name: pipeline-test
env:
  track-name: pipeline-test
on:
  workflow_dispatch: # Manual trigger
    inputs:
      also-release:
        description: 'Run RELEASE if this attribute is `true`'     
        required: true
        default: 'false'
jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-cli
      - uses: actions/upload-artifact@v2
        with:
          name: instruqt-cli
          path: instruqt
  build:
    needs: [prepare]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: instruqt-cli
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/instruqt
      - uses: ./.github/actions/create-ephemeral-track
        with:
          track-name: ${{ env.track-name }}
          ephemeral-track-name: ci-${{ env.track-name }}-tmp
          token: ${{ secrets.INSTRUQT }}
  test:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: instruqt-cli
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/instruqt
      - uses: ./.github/actions/test-track
        with:
          track-name: ci-${{ env.track-name }}-tmp
          token: ${{ secrets.INSTRUQT }}
  deploy:
    if: ${{ github.event.inputs.also-deploy == 'true' }}
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: instruqt-cli
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/instruqt
      - uses: ./.github/actions/push-track
        with:
          track-name: ${{ env.track-name }}
          token: ${{ secrets.INSTRUQT }}
  tear-down:
    if: always()
    needs: [deploy]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: instruqt-cli
          path: /usr/local/bin
      - run: chmod +x /usr/local/bin/instruqt
      - uses: ./.github/actions/delete-track
        with:
          track-name: ci-${{ env.track-name }}-tmp
          token: ${{ secrets.INSTRUQT }}
